### PR TITLE
Feature/#577 add detail to network actions

### PR DESCRIPTION
**Pull request by jonzfisher**
Adding:
* Priority (enum)
* Status (enum)
* Owner (User)
* Update NetworkAction model to include priority, status, and owner
* Account for nils on the show and index views

### CODE REVIEW

**Comment by jonzfisher** [comment]
Whoops, didn't mean to assign you! Just for review. 👍

**Comment by jonzfisher** [comment]
Resolved a conflict in the schema

**Comment by jonzfisher** [comment]
Alright @anthonycrumley should be good to go now for review if you're interested!

**Comment by anthonycrumley** [comment]
@jonzfisher Thanks for helping Birmingham's children!!

**Pull request merged**
