### PR TITLE
Remove participant from event

### PR DESCRIPTION
**Pull request by acsellers**

### CODE REVIEW

**Comment by acsellers** [comment]
AKA Issue 145

**Comment by rthbound** [comment]
#145 

@acsellers github's got some cool integrations... you can just mention `#145` and github will add a "references"/"referenced by" link to both issues

**Comment by rthbound** [comment]
@acsellers bonus: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by anthonycrumley** [comment]
@acsellers Thanks for all you do to help Birmingham's kids!!!

**Pull request merged**
