### PR TITLE
Require Authentication for certain client-side controllers

### LINKED ISSUE #140: From the signin page I am able to update the url and go to the new members page.
I was at the sign in page. Haven't successfully signed in yet. But, simply changing the url from /signin to /members/create ->brought me to this page. See attached. 
1-14-2016 11-31-31 ammembers_create

### PR DESCRIPTION
**Pull request by jzw**
fixes #140

### CODE REVIEW

**Comment by anthonycrumley** [comment]
@jzw Thanks for giving of your time to Birmingham's kids!!!

**Comment by anthonycrumley** [comment]
@jzw Would you like to become an maintainer of the Network project?  The responsibilities of maintainers are documented in the [Collective Code Construction Contract](https://github.com/edbirmingham/network/blob/master/c4.md).  Thanks again for your contribution.  :+1:

**Comment by jzw** [comment]
@anthonycrumley yes!

**Comment by anthonycrumley** [comment]
@jzw Thanks!!  You have commit access and can merge correct pull requests.

**Pull request merged**
