### PR TITLE
List

### PR DESCRIPTION
**Pull request by TadBirmingham**

### CODE REVIEW

**Comment by rthbound** [comment]
I can tell already this will conflict with #116 ... Powers that be, @anthonycrumley, if you want to merge this one, I'll rebase #116 to add the remaining fields (this one takes care of event type on the events list).

**Comment by TadBirmingham** [comment]
Sorry @rthbound ! New to this whole process so I apologize if I have caused more work or created overlap - or both it sounds like.

**Comment by rthbound** [comment]
@TadBirmingham no problem at all! There's some overlap, but the issue I was after was about adding fields to the events list. If you'll just add the remaining fields described in the ticket #105 then I can just close #116. What do you think?

**Comment by rthbound** [comment]
:+1: @TadBirmingham would you mind to [squashing](http://stackoverflow.com/a/5189600/1152759) your commits, then `git push -f` to your feature branch?

**Comment by anthonycrumley** [comment]
Thanks for helping Birmingham's kids!!!  :+1:

**Comment by anthonycrumley** [comment]
@TadBirmingham These changes have been released.  :+1:

**Pull request merged**
