### PR TITLE
Mongo startup

### PR DESCRIPTION
**Pull request by andreburto**
Script for #127

### CODE REVIEW

**Comment by anthonycrumley** [comment]
@andreburto This is really awesome.  I am looking forward to using it.

Suggestions:
* Make the file executable.
* Remove the .sh suffix
* Check for the web server already running.

**Comment by andreburto** [comment]
@anthonycrumley I made the changes per your suggestion.

**Comment by anthonycrumley** [comment]
@andreburto Excellent!!  :+1:

**Comment by anthonycrumley** [comment]
@andreburto Thanks for believing in Birmingham's kids!!!

**Pull request merged**
