### PR TITLE
Member date filter

### PR DESCRIPTION
**Pull request by saabdoli**
Add ability to filter members by date

### CODE REVIEW

**Comment by anthonycrumley** [comment]
@saabdoli Thanks for everything you do for Birmingham's kids!!!

**Comment by anthonycrumley** [comment]
@saabdoli Would you like to become an maintainer of the Network project?  The responsibilities of maintainers are documented in the [Collective Code Construction Contract](https://github.com/edbirmingham/network/blob/master/c4.md).  Thanks again for your contribution.  :+1:

**Comment by saabdoli** [comment]
Yes, I would like to become a maintainer.

Thanks!

**Comment by anthonycrumley** [comment]
@saabdoli You have permission to commit.  Feel free to merge correct pull requests.  :smile:

**Pull request merged**
