### PR TITLE
Filter actions by owner and actor

### PR DESCRIPTION
**Pull request by jonzfisher**
Change Log
* add filter method for the index page
* add test for filter
* add form to do the filter action

### CODE REVIEW

**Comment by jonzfisher** [comment]
I need to update this: I mistakenly filtered on Actor instead of Owner, so I'll expand this for owner soon.

**Comment by jonzfisher** [comment]
hey @anthonycrumley! I've fixed Owner now and added Actor. Should be good to go! Let me know if you have any feedback!

image

**Comment by jonzfisher** [comment]
This week: I've corrected the Actors field on the index page of Network's Actions to search instead of querying all members.

Next week: Would like to implement suggestion by anthony to split the parameters into search and update parameters

**Comment by anthonycrumley** [comment]
@jonzfisher Thanks for contributing to help Birmingham's school children!!

**Pull request merged**
