### PR TITLE
Added a multiselect to the Actions list page

### PR DESCRIPTION
**Pull request by atcrawford**
Added a multiselect to the Actions list page to allow filtering by Action Status; Wired up the backend to include the selected values when it performs the query.

This work connects to #167.

### CODE REVIEW

**Comment by atcrawford** [comment]
Demo of the new multiselect

**Comment by anthonycrumley** [comment]
@atcrawford How did you make that screencast? It is super helpful to be able to see how the change works.

**Comment by anthonycrumley** [comment]
@atcrawford Thanks for believing in Birmingham's kids!!!

**Comment by atcrawford** [comment]
I have a personal license for Screencast-o-matic. It makes it really easy to make gifs like that, or even longer screencasts. There are free options out there too, but this one was worth purchasing in my book. 😊

https://screencast-o-matic.com/

**Comment by anthonycrumley** [comment]
@joymac Checkout the screen cast above and the recorder @atcrawford used to make it.

**Comment by anthonycrumley** [comment]
@atcrawford Thanks for the recommendation.  I am going to try it out.

**Pull request merged**
